### ISSUE TITLE
linear_regression.py文件报错，运行环境2.7/3.6均失败

### ISSUE THREAD

**Issue by LionCoder4ever** [yoyoyohamapi/mit-ml#3]
Traceback (most recent call last):
  File "/home/kkk/code/mit-ml-master/linear_regression/test_sgd.py", line 11, in <module>
    X, y = regression.loadDataSet('data/ex1.txt');
  File "/home/kkk/code/mit-ml-master/linear_regression/regression.py", line 39, in loadDataSet
    y.append(float(curLine[-1]))
ValueError: invalid literal for float(): 6.1101  17.592

**Comment by yoyoyohamapi** [comment]
@LionCoder4ever 数据格式错误，已修复，更新下试试
